### ISSUE TITLE
Ardupilot Install

### ISSUE THREAD

**Issue by justinnuwin** [justinnuwin/NGCP-Capstone-UGV#11]
Deliverables:

- Ardupilot on the Nano so we can communicate with the Pixhawk (https://ardupilot.org/dev/docs/ros.html)

**Comment by alexgarcia98** [comment]
useful thread: https://discuss.ardupilot.org/t/nvidia-jetson-nano-for-pixhawk/46052

**Comment by justinnuwin** [comment]
https://github.com/mavlink/mavros/tree/master/mavros#installation Looks like we'll need to build from source as they don't have binaries for aarch64

**Comment by justinnuwin** [comment]
Got mavros installed, but had to move the build and devel folders due to a conflict with `catkin make` and `catkin build`. In the build process `catkin build` was run which looks like it is rebuilding the other ROS nodes. We'll have to test the LiDAR and ZED Camera after installation.

**Comment by alexgarcia98** [comment]
Tested LiDAR and ZED camera, still operate after installation.
