### ISSUE TITLE
PixHawk Setup 

### ISSUE THREAD

**Issue by justinnuwin** [justinnuwin/NGCP-Capstone-UGV#12]
Deliverables:

- Get the PixHawk setup with Ardupilot
- Test to make sure the PixHawk communicates with Arudpilot and ROS running on the Nano

**Comment by justinnuwin** [comment]
Using QGroundcontrol (QGC) to communicate with Pixhawk and update its firmware. https://docs.qgroundcontrol.com/en/getting_started/download_and_install.html

**Comment by justinnuwin** [comment]
To implement Mavlink we'll have our computers act as the GCS (QGC) and communicate to the Nano running Mavros over the network

**Comment by justinnuwin** [comment]
@gencurio after you get QGC follow this to update the firmware on the PX4 https://docs.px4.io/v1.9.0/en/config/firmware.html

**Comment by justinnuwin** [comment]
Currently the architecture looks like so:

```
GSC ---network---> mavros (nano) ---> ROS ----usb nano------> LiDAR and ZED camera
                                       |
                                       |---microusb----> px4 ------> car and GPS
 ```

**Comment by gencurio** [comment]
Flashed ChibiOS- ArduRover V4.0.0 using QGroundControl v3.5.6 for MacOS

**Comment by gencurio** [comment]
Unable to arm pixhawk with driving commands from QGroundControl, QGC is aware that our test car doesn't have a GPS and has failsafes to prevent driving without a GPS.

**Comment by gencurio** [comment]
We are investigating using python-Dronekit library as a Ground Control Station so that we can avoid any failsafe features.

**Comment by gencurio** [comment]
Tiana mentioned that NGCP has spare GPS units if we need one for testing.

**Comment by justinnuwin** [comment]
We got the PX4 working, but we havn't cleared up uwhether they are using the PX4 or PixHawk mini.
