### ISSUE TITLE
ROS Sensor Fusion Node

### ISSUE THREAD

**Issue by gencurio** [justinnuwin/NGCP-Capstone-UGV#13]
We need to setup a ROS Node that can subscribe to each sensor and combine the data we receive to make informed decisions on what the car should do next.

**Comment by gencurio** [comment]
Here is a github repo that discusses sensor fusion within ROS: https://github.com/methylDragon/ros-sensor-fusion-tutorial

**Comment by justinnuwin** [comment]
This is handled by RTABmap
