### ISSUE TITLE
Sensor Frame Transformations

### ISSUE THREAD

**Issue by justinnuwin** [justinnuwin/NGCP-Capstone-UGV#14]
Used this tutorial: http://wiki.ros.org/navigation/Tutorials/RobotSetup/TF

Overview of the tf package: http://wiki.ros.org/tf/Tutorials/Introduction%20to%20tf

I just commited the broadcaster. @gencurio to upload measurements to repo.

**Comment by gencurio** [comment]
Completed measurement calculations:
base_link -> base_lidar: (0, 0, 0, 1) Quaternians, (0.105m, -0.105m, 0m) Vector3
base_link -> base_zed: (0, 0, 0, 1) Quaternians, (0.16m, 0.085m, 0m) Vector3

**Comment by gencurio** [comment]
Noticed values are already in tf_broadcaster.cpp, but in cm. Converting to meters.

**Comment by gencurio** [comment]
Used listener example from the tutorial to create a listener for lidar and zed values. Now creating a ROS package to encapsulate the transform cpp files.

**Comment by gencurio** [comment]
Commited ROS package named bugv_tf that contains tf_broadcaster and tf_receiver nodes and confirmed that values are being transformed.

**Comment by gencurio** [comment]
[For Future Reference] : Hardware Measurement Diagram
![IMG_0251](https://user-images.githubusercontent.com/2148289/73405487-dee96c80-42a8-11ea-80b0-bfe4907244b6.jpg)

**Comment by justinnuwin** [comment]
Got our TF added to the ros launch config, but there seems to be issues relating the robot "base_link" frame with the map frame coming from ZED. Alex and I will investigate the ZED urdf node which seems to be publishing transformation data.

**Comment by justinnuwin** [comment]
Got TF to relate the zed frame to the base_link frame by looking at the zed_camera.launch config once again. A node called zed_state_publisher publishes a transformation from `robot_description` to `zed_description`. Updating bugv_tf to publish `base_link` to `robot_description` and `base_link` to `zed_description` we override the zed tf (I think?) and links the robot base_frame and the camera together. This was tested by moving the camera against the `odom` frame which is the starting point and checking that the frames were aligned and moved together.
