### ISSUE TITLE
Flashing Jetson Nano With Jetpack

### ISSUE THREAD

**Issue by gencurio** [justinnuwin/NGCP-Capstone-UGV#2]
Goal is to install an ubuntu version compatible with ROS Kinetic, RPLidar, and Zed Mini

**Comment by gencurio** [comment]
Downloading Ubuntu 16.04, which is required for ROS Kinetic and Andy has confirmed that this version works with the RPLidar. Assuming that this version will also work with Zed Mini.

**Comment by gencurio** [comment]
Ended up actually installing Ubuntu 18.04 after realizing that Zed Mini should be compatible with ROS Melodic. Need to confirm RPLidar and Zed Mini are working.

**Comment by justinnuwin** [comment]
Good job! Tested the install by making some of the CUDA samples and they worked. Closing this issue. Next steps are installing ROS and creating a backup image.

**Comment by justinnuwin** [comment]
By the way the Nano uses CUDA 10.

**Comment by gencurio** [comment]
By the way, I didn't need to use Jetpack to setup the Nano. Instead I followed the steps on this page to flash the sd card with an image of linux: https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit#write
