### ISSUE TITLE
Test ZED Mini with Jetson Nano

### ISSUE THREAD

**Issue by alexgarcia98** [justinnuwin/NGCP-Capstone-UGV#5]

**Comment by justinnuwin** [comment]
See #4 a StereoLabs tutorial was used to install ROS and the ROS node for the camera. SDK installation too.

**Comment by gencurio** [comment]
Ran into error with libusb-0.1. Installed library libusb-0.1 and confirmed the the imu was working. Haven't been able to get an image to display in rvis just yet.

**Comment by justinnuwin** [comment]
Zed Camera works. IMU and RTAB orientation seems to be working. Going through the different settings in the ROS rviz displays can't seem to pull any additional data out of the camera. Looks like the camera works fully. Steps forward will be to get sensor fusion working.

Command to run test: `roslaunch zed_display_rviz display_zedm.launch`

![Screenshot from 2020-01-12 16-47-59](https://user-images.githubusercontent.com/10904757/72228452-979a7680-355b-11ea-9dca-b9f6f26aba3a.png)
