### ISSUE TITLE
ZED RTAB-Map

### ISSUE THREAD

**Issue by justinnuwin** [justinnuwin/NGCP-Capstone-UGV#7]
Either find a ROS node to do this or write one

**Comment by alexgarcia98** [comment]
rtab_map is included with ros, sample code has already been downloaded. Instructions to run are found here: http://wiki.ros.org/rtabmap_ros/Tutorials/HandHeldMapping

**Comment by justinnuwin** [comment]
This is completed with bugv_rtab node
