### ISSUE TITLE
RPLiDAR + Rtabmap

### ISSUE THREAD

**Issue by justinnuwin** [justinnuwin/NGCP-Capstone-UGV#8]
Either find a ROS node to do this or write one.

**Comment by andy805** [comment]
To setup the the rplidar on ros
1. clone https://github.com/Slamtec/rplidar_ros into your workspace in the src directory
2. run "catkin_make" to build rplidar node and rplidarnode client
3. `$ sudo usermod -a -G dial out <username>`
4. Reboot

**Comment by gencurio** [comment]
Here is a video on setting up an older RPLidar for Hector SLAM with ROS: https://www.youtube.com/watch?v=Qrtz0a7HaQ4

**Comment by justinnuwin** [comment]
Bugv_rtab is subscribed to /rplidar/scan which publishes the laser scan data. It seems it is working, (transparently) since the frames have been aligned. THere is no indication that it is working (rviz not displaying the laser scan points). Needs some additional testing.

**Comment by justinnuwin** [comment]
Once frames are aligned. occupancy grid works as expected.
